select order_line from sale_order where id=930757;

select sol.product_id 
from sale_order so
inner join sale_order_line sol
on so.id = sol.order_id
where so.id=930757;

select pp.default_code
from sale_order so
inner join sale_order_line sol
on so.id = sol.order_id
inner join product_product pp
on sol.product_id=pp.id
where so.id = 930757;

select pp.default_code, pt.name, pp.weight, 
from sale_order so
inner join sale_order_line sol
on so.id = sol.order_id
inner join product_product pp
on sol.product_id=pp.id
inner join product_template pt
on pp.product_tmpl_id=pt.id
where so.id = 930757;

select pp.default_code, sm.product_uom_qty, pp.weight, pt.name, sm.product_uom_qty*pp.weight
from stock_picking sp
inner join stock_move sm
on sp.id = sm.picking_id
inner join product_product pp
on sm.product_id=pp.id
inner join product_template pt
on pp.product_tmpl_id=pt.id
where sp.id = 944981;
